# Copyright 2020-2021 The MathWorks, Inc
name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.sha}}

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        # Installing wheel package will slightly speed-up installing dependencies.
        # Installing the package with "[dev]" flag  will install test dependecies as well,
        # enabling us to run pytest.
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install .[dev]

      - name: Run Python Tests
        run: python -m pytest

  build_and_publish_pypi:
    needs: [python_tests]
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.sha}}

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel hatch

      - name: Build Source and Binary wheel distributions
        run: python -m hatch build -t wheel

      - name: Publish to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          verbose: true
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: ${{ secrets.PYPI_REPOSITORY_URL }}