# Copyright 2024 The MathWorks, Inc.
name: Test TLJH-MATLAB package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Package
      run: |
        cd ./install_guides/the-littlest-jupyterhub/tljh-matlab
        python -m pip install .

    - name: Lint with flake8
      run: |
        cd ./install_guides/the-littlest-jupyterhub/tljh-matlab
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Lint with black
      run: black --check ./install_guides/the-littlest-jupyterhub/tljh-matlab

    - name: Test with unittest
      run: |
        python -m unittest discover --verbose -s ./install_guides/the-littlest-jupyterhub/tljh-matlab
